# Generated by Django 4.1 on 2022-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_spacex_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacex',
            name='Count',
        ),
    ]
